### ISSUE TITLE
I cant get in when using this plugin

### ISSUE THREAD

**Issue by HJDCZY** [Flamtky/fivem-respawn-nearby#2]
I can't get in my fivem server when using this plugin. It keeps "awaiting scripts" and can't get in when I try to enter my server. 
my server console is like this
> ensure "fivem-respawn-nearby"
[ citizen-server-impl] Stopping resource fivem-respawn-nearby
[   script:mapmanager] Started gametype My awesome game type!
[ citizen-server-impl] Started resource fivem-respawn-nearby

and before I ensure this script, fivem-map-skater (1.0.0) and basic-gamemode is started

How can I solve it?

**Comment by Flamtky** [comment]
I added a small workaround in the newest version.
If the error still occurs, feel free to reopen this issue again
