### ISSUE TITLE
Only Backup Point on Latest Canary FiveM Game version 3095

### ISSUE THREAD

**Issue by Unkn0wnCreator** [Flamtky/fivem-respawn-nearby#3]
Hi,

I do not know if it is something I did wrong, but I simply put the mod like any other in resources and put it in the server.cfg and in game I am only spawning at the Backup point.

**Comment by Flamtky** [comment]
Hey @Unkn0wnCreator ,

Thanks for reporting this issue. I've tried reproducing it on version 3095 without success. Please note that 3095 is currently unstable (afaik). Maybe an update to the latest version can fix your issue, or even wait for a stable release, and test again? If the problem persists, please share your `server.cfg` file, making sure to remove any sensitive information, so I can look into it further.

Additionally, you can debug the script yourself using the `DEBUG_PRINT` variable. This will print blips on the map to verify if points are being found. Also, check your console (default key: F8) after respawning for any errors.

**Comment by Unkn0wnCreator** [comment]
I have disabled all additional resources and tested it multiple times. I am spawning at the default backup coordinates, and I've set `DEBUG_PRINT = true`. However, I do not see anything in F8 or on the map. 

The only thing I am seeing is:

`[     11203] [b3095_GTAProce]  UV loop: httpClient/ Required resources: sessionmanager mapmanager yarn webpack chat spawnmanager basic-gamemode fivem hardcap rconlog playernames fivem-respawn-nearby fivem-map-hipster `

and 
`[     29313] [b3095_GTAProce]             MainThrd/ Creating script environments for fivem-respawn-nearby`


my `server.cfg` https://bin.nixnet.services/?d033076609cd573f#2VDRSa9AKACTGuiyVxRPi6MGcmeWra7QzjKf6Awat76G

Maybe I've overlooked something in my `server.cfg`, or something other is the problem

I also have cleared Cache on the Server and Client

Edit:
I am using this Docker Container https://github.com/ich777/docker-fivem-server.

Edit2:

ive did some more Testing, i have stopped the Resource by /stop fivem-respawn-nearby and restarted it via /start fivem-respawn-nearby

this is the log:

    184563] [b3095_GTAProce]             MainThrd/ Stopping resource fivem-respawn-nearby
[    184563] [b3095_GTAProce]             MainThrd/ 
[    189407] [b3095_GTAProce]             MainThrd/ Started gametype Freeroam
[    189407] [b3095_GTAProce]             MainThrd/ Started resource fivem-respawn-nearby
[    189407] [b3095_GTAProce]             MainThrd/ 
[    189422] [b3095_GTAProce]             MainThrd/ OnConnectionProgress: Downloading content manifest...
[    189422] [b3095_GTAProce]  UV loop: httpClient/ Required resources: fivem-respawn-nearby 
[    189453] [b3095_GTAProce]             MainThrd/ Creating script environments for fivem-respawn-nearby
[    189469] [b3095_GTAProce]             MainThrd/ OnConnectionProgress: Mounted fivem-respawn-nearby (1 of 1)
[    239907] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: error object is not a string^7

and I Can't respawn anymore.

![image](https://github.com/Flamtky/fivem-respawn-nearby/assets/84105345/6d0d54e2-6e36-4291-afa2-dc23a38a181a)

Edit3:

when using ur latest Dev version than i can press u and it works but my char model is invisible. sadly when i die for example from granade or suicide with vmenu then i will always spawn x = 0, y = 0, z = 70

**Comment by Flamtky** [comment]
@Unkn0wnCreator 
Thanks for the detailed updates and your efforts in troubleshooting. I'd recommend testing the latest development branch of the script. I've completely rewritten the entire script, and while I haven't been able to reproduce your specific issue, your input could be helpful.

Please note that this development branch might still have some bugs, as it's under active development. Despite this, the script should function as expected.

To proceed, switch to the new development branch and give it a try. After testing, any feedback, especially on any persisting issues or new ones that arise, would be greatly appreciated. This will help in further refining the script.

**Comment by Flamtky** [comment]
I'm a bit busy with other projects at the moment, so this may take a while. The problem is that **I can't reproduce this error**, but it would need some further testing. In the dev branch you can also find a newer version that worked for me (version 3095). Otherwise we would have to test if it is due to the Docker version of the server or if another plugin is causing the problem for me or you.

**Comment by Flamtky** [comment]
I've decided to close this issue as I can't reproduce the error.

Please test the latest script update. If the issue persists, try deactivating other plugins to identify any conflicts. If the problem continues, reopen this issue with more details.

Thank you.
